// <auto-generated />
using System;
using Agreement_Management.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Agreement_Management.Migrations
{
    [DbContext(typeof(ApplicationDContext))]
    [Migration("20220920153414_newtable")]
    partial class newtable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Agreement_Management.Models.Agreement", b =>
                {
                    b.Property<int>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("New_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Product_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("productGroupId")
                        .HasColumnType("int");

                    b.HasKey("AgreementId");

                    b.HasIndex("ProductId");

                    b.HasIndex("productGroupId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("Agreement_Management.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Product_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Product_Number")
                        .HasColumnType("int");

                    b.Property<int?>("productGroupId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("productGroupId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Agreement_Management.Models.ProductGroup", b =>
                {
                    b.Property<int>("productGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Group_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group_Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productGroupId");

                    b.ToTable("ProductGroups");
                });

            modelBuilder.Entity("Agreement_Management.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Agreement_Management.Models.Agreement", b =>
                {
                    b.HasOne("Agreement_Management.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Agreement_Management.Models.ProductGroup", "ProductGroupId")
                        .WithMany()
                        .HasForeignKey("productGroupId");
                });

            modelBuilder.Entity("Agreement_Management.Models.Product", b =>
                {
                    b.HasOne("Agreement_Management.Models.ProductGroup", "ProductGroupId")
                        .WithMany()
                        .HasForeignKey("productGroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
